### ISSUE TITLE
exception while trying to run SWA local instance

### ISSUE THREAD

**Issue by khaledm** [Azure/static-web-apps-cli#313]
Hi - trying to create a vanilla starter SWA based on the instructions here: https://docs.microsoft.com/en-gb/azure/static-web-apps/getting-started?tabs=vanilla-javascript

when I try to run it locally I'm getting following exception:

C:\Users\XXXX\AppData\Roaming\npm\node_modules\@azure\static-web-apps-cli\dist\core\utils\net.js:42
    catch {
          ^

SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:152:10)
    at Module._compile (module.js:624:28)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\XXXX\AppData\Roaming\npm\node_modules\@azure\static-web-apps-cli\dist\core\constants.js:9:15)

I've installed  the Azure Static Web Apps CLI/emulator and Azure Functions Core Tools V3.

**Comment by manekinekko** [comment]
@khaledm looks like you are having a Node.js version mismatch. Please make sure you are using [Node.js v14 LTS](https://nodejs.org/ko/blog/release/v14.16.0/) or latest.

Also, please fill in the issue template so we can have all the required information in order to assist you.

**Comment by khaledm** [comment]
@manekinekko thanks for the pointer, should've checked https://docs.microsoft.com/en-gb/azure/azure-functions/functions-reference-node?tabs=v2#node-version here first.
