### ISSUE TITLE
Routing with asterisk: SyntaxError: Invalid regular expression: /^*$/

### ISSUE THREAD

**Issue by Deathrage** [Azure/static-web-apps-cli#569]
I have this config:
```json
{
  "platform": {
    "apiRuntime": "node:16"
  },
  "routes": [
    {
      "route": "/.auth/login/facebook",
      "statusCode": 404
    },
    {
      "route": "/.auth/login/google",
      "statusCode": 404
    },
    {
      "route": "/.auth/login/twitter",
      "statusCode": 404
    },
    {
      "route": "/.auth/login/github",
      "statusCode": 404
    },
    {
      "route": "*",
      "allowedRoles": ["registered_user"]
    }
  ],
  "responseOverrides": {
    "401": {
      "statusCode": 302,
      "redirect": "/.auth/login/aad"
    }
  },
  "navigationFallback": {
    "rewrite": "/"
  }
}
```

When I run `swa start` and visit webapp, the process exists with 1. From JavaScript Debug Terminal I caught this exception:
```
Exception has occurred: SyntaxError: Invalid regular expression: /^*$/: Nothing to repeat
  at new RegExp (<anonymous>)
    at doesRequestPathMatchWildcardRoute (C:\Users\Ja\AppData\Roaming\npm\node_modules\@azure\static-web-apps-cli\dist\msha\routes-engine\route-processor.js:89:20)
    at doesRequestPathMatchRoute (C:\Users\Ja\AppData\Roaming\npm\node_modules\@azure\static-web-apps-cli\dist\msha\routes-engine\route-processor.js:36:62)
    at tryGetMatchingRoute (C:\Users\Ja\AppData\Roaming\npm\node_modules\@azure\static-web-apps-cli\dist\msha\routes-engine\rules\routes.js:111:63)
    at requestMiddleware (C:\Users\Ja\AppData\Roaming\npm\node_modules\@azure\static-web-apps-cli\dist\msha\middlewares\request.middleware.js:188:71)
    at Server.<anonymous> (C:\Users\Ja\AppData\Roaming\npm\node_modules\@azure\static-web-apps-cli\dist\msha\server.js:36:58)
    at Server.emit (node:events:520:28)
    at parserOnIncoming (node:_http_server:951:12)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:128:17)
``` 

Emulator produces invalid RegExp from the route containing asterisk (see above). Azure Static Web Apps accept asterisk as a wildcard. Emulator should accept it aswell. Proper RegExp is `/^.*$/`.

**Comment by Deathrage** [comment]
Changing problematic route to `/*` will fix the issue. However I do think that emulator should behave as closely to Azure Statci Web Apps as possible.
