### ISSUE TITLE
swa deploy hangs at "Preparing deployment. Please wait"

### ISSUE THREAD

**Issue by derkoe** [Azure/static-web-apps-cli#615]
**Describe the bug**

When running:
```
npx swa deploy --no-use-keychain -d {deployment-token}
```

It hangs on `Preparing deployment. Please wait...`

Full output is (with `--verbose=silly`):
```
Welcome to Azure Static Web Apps CLI (1.0.3)

Getting config file options from swa-cli.config.json...
Changed directory to /folder
Using configuration "qwik-app" from file:
  /folder/swa-cli.config.json

Deploying front-end files from folder:
  /folder/dist

Deploying API from folder:
  /folder/dist

Deployment token provided via flag
 - --deployment-token: <hidden>

Deploying to environment: preview

Trying to read workflow config with values:
 - appLocation: /folder/dist
 - outputLocation: /folder/dist
 - apiLocation: /folder/dist
No workflow config folder found at /folder/dist/.github/workflows
Validating user workflow config (BEFORE):
 - appLocation: /folder/dist
 - outputLocation: /folder/dist
 - apiLocation: /folder/dist
Validating user workflow config (AFTER):
 - appLocation: /folder/dist
 - apiLocation: /folder/dist
 - outputLocation: /folder/dist
Loading staticwebapp.config.json schema...
Schema loaded successfully from https://json.schemastore.org/staticwebapp.config.json
Compiling schema...
Reading content from staticwebapp.config.json...
Parsing staticwebapp.config.json...
Validating staticwebapp.config.json...
File validated successfully. Continuing with configuration!
Content parsed successfully

Found configuration file:
  /folder/dist/staticwebapp.config.json

Deploying project to Azure Static Web Apps...
Fetching release metadata for version: stable. Please wait...
 - version: stable
 - buildId: 1.0.020981
 - publishDate: 2022-09-29T17:37:34.4094014Z
- files:
 - linux-x64:
   - url: https://swalocaldeploy.azureedge.net/downloads/1.0.020981/linux/StaticSitesClient
   - sha: e55db21d0720a12098804559152303e66846bdd94c13a30b30be29a0fc9ae366
 - win-x64:
   - url: https://swalocaldeploy.azureedge.net/downloads/1.0.020981/windows/StaticSitesClient.exe
   - sha: 4e4eb72aef26641e236c24929c822500e956bda099ca78054112cadf20261107
 - osx-x64:
   - url: https://swalocaldeploy.azureedge.net/downloads/1.0.020981/macOS/StaticSitesClient
   - sha: e0f2ae7ec297510a1b3b9332c0dc0dd962a51adb8ea13cd4f3746d79fc24a7e9
Local client binary is up to date. Skipping download.
Deploying using /home/user/.swa/deploy/1.0.020981/StaticSitesClient@1.0.020981
Deploying using the following options:
- env:
  - SWA_CLI_DEBUG: silly
  - SWA_RUNTIME_WORKFLOW_LOCATION: <undefined>
  - SWA_RUNTIME_CONFIG_LOCATION: /folder/dist
  - SWA_RUNTIME_CONFIG: /folder/dist/staticwebapp.config.json
  - SWA_CLI_VERSION: 1.0.3
  - SWA_CLI_DEPLOY_DRY_RUN: false
  - SWA_CLI_DEPLOY_BINARY: /home/user/.swa/deploy/1.0.020981/StaticSitesClient@1.0.020981
  - DEPLOYMENT_ACTION: upload
  - DEPLOYMENT_PROVIDER: SwaCli
  - REPOSITORY_BASE: /folder/dist
  - SKIP_APP_BUILD: true
  - SKIP_API_BUILD: true
  - DEPLOYMENT_TOKEN: <hidden>
  - APP_LOCATION: /folder/dist
  - API_LOCATION: /folder/dist
  - CONFIG_FILE_LOCATION: /folder/dist
  - VERBOSE: true
  - DEPLOYMENT_ENVIRONMENT: preview
⠧ Preparing deployment. Please wait...
```

**To Reproduce**

1. Create a static webapp with API
2. Create a `swa-cli.config.json` containing:
    ```
    {
      "$schema": "https://aka.ms/azure/static-web-apps-cli/schema",
      "configurations": {
        "qwik-app": {
          "appName": "qwik-app",
          "appLocation": "./dist",
          "apiLocation": "./dist",
          "appBuildCommand": "npm run build",
          "apiBuildCommand": "npm run build.server"
        }
      }
    }
   ``` 
4. Run `npx swa deploy --no-use-keychain -d {deployment-token}`
5. The deployment hangs on `Preparing deployment. Please wait...`

**Expected behavior**
Deploy with `swa` CLI should work.

**Desktop (please complete the following information):**

- OS: Windows 
- Version 11
- WSL2: 1.0.0.0
- WSL Distro: Ubuntu 22.10

**Comment by manekinekko** [comment]
@derkoe Can you share a link to your repo (or similar reproduction repo) so we can investigate this issue?

**Comment by derkoe** [comment]
@manekinekko you can take any repository - it fails with all. Just take a folder with an index.html

**Comment by manekinekko** [comment]
Just did: https://kind-river-0644df51e-preview.westus2.2.azurestaticapps.net

<details>
  <summary>Full Logs</summary>

```
➜  swa-issue-615 npx @azure/static-web-apps-cli@1.0.3 init
Need to install the following packages:
  @azure/static-web-apps-cli@1.0.3
Ok to proceed? (y)

Welcome to Azure Static Web Apps CLI (1.0.3)

✔ Choose a configuration name: … swa-issue-615

Detected configuration for your app:
- Framework(s): Static HTML
- App location: public
- Output location: .
- API location:
- App build command:
- API build command:
- App dev server command:
- App dev server URL:

✔ Are these settings correct? … yes

Configuration successfully saved to swa-cli.config.json.

Get started with the following commands:
- Use swa start to run your app locally.
- Use swa deploy to deploy your app to Azure.

➜  swa-issue-615 swa deploy --no-use-keychain --verbose silly

Welcome to Azure Static Web Apps CLI (1.0.3-alpha)

Getting config file options from swa-cli.config.json...
Changed directory to /tmp/swa-issue-615
Using configuration "swa-issue-615" from file:
  /tmp/swa-issue-615/swa-cli.config.json

Deploying front-end files from folder:
  /tmp/swa-issue-615/public

No deployment token found. Trying interactive login...
Checking Azure session...
Executing authenticateWithAzureIdentity
- details:
  - tenantId: <undefined>
  - clientId: <undefined>
  - clientSecret: <undefined>
 - useKeychain: false
Keychain is disabled
✔ Successfully logged into Azure!
Found 1 tenant: xyz
Selected tenant: xyz
✔ Choose your subscription › ca-wachegha-demo-test
Selected subscription: xyz
Project credentials:
 - subscriptionId: xyz
 - tenantId: xyz
 - clientId: <undefined>
 - clientSecret: <undefined>
✔ Saved project credentials in .env file.
No .gitignore file found. Skip updating .gitignore
Login successful

Checking project settings...
choose static site with initial: undefined
✔ Choose your Static Web App › >> Create a new application
✔ Choose a project name: … swa-issue-615
⠋ Creating a new project...Resource group "swa-issue-615-rg" does not exist. Creating one...
⠹ Creating a new project... - id: /subscriptions/xyz/resourceGroups/swa-issue-615-rg
 - name: swa-issue-615-rg
 - type: Microsoft.Resources/resourceGroups
- properties:
  - provisioningState: Succeeded
 - location: westus2
Checking if project "swa-issue-615" already exists...
⠼ Creating a new project...Caught error: The Resource 'Microsoft.Web/staticSites/swa-issue-615' under resource group 'swa-issue-615-rg' was not found. For more details please go to https://aka.ms/ARMResourceNotFoundFix
Creating static site "swa-issue-615" in resource group "swa-issue-615-rg"...
⠙ Creating a new project...Static site "swa-issue-615" created successfully.
 - id: /subscriptions/xyz/resourceGroups/swa-issue-615-rg/providers/Microsoft.Web/staticSites/swa-issue-615
 - name: swa-issue-615
 - location: West US 2
 - type: Microsoft.Web/staticSites
- sku:
  - name: Free
  - tier: Free
 - defaultHostname: kind-river-0644df51e.2.azurestaticapps.net
 - repositoryUrl:
 - branch:
- customDomains:
- privateEndpointConnections:
 - stagingEnvironmentPolicy: Enabled
 - allowConfigFileUpdates: true
 - contentDistributionEndpoint: https://content-wus2.infrastructure.2.azurestaticapps.net
 - keyVaultReferenceIdentity: SystemAssigned
- userProvidedFunctionApps:
 - provider: None
 - enterpriseGradeCdnStatus: Disabled
✔ Project created successfully!
Static site found!
- staticSite:
  - id: /subscriptions/xyz/resourceGroups/swa-issue-615-rg/providers/Microsoft.Web/staticSites/swa-issue-615
  - name: swa-issue-615
  - location: West US 2
  - type: Microsoft.Web/staticSites
 - sku:
   - name: Free
   - tier: Free
  - defaultHostname: kind-river-0644df51e.2.azurestaticapps.net
  - repositoryUrl:
  - branch:
 - customDomains:
 - privateEndpointConnections:
  - stagingEnvironmentPolicy: Enabled
  - allowConfigFileUpdates: true
  - contentDistributionEndpoint: https://content-wus2.infrastructure.2.azurestaticapps.net
  - keyVaultReferenceIdentity: SystemAssigned
 - userProvidedFunctionApps:
  - provider: None
  - enterpriseGradeCdnStatus: Disabled
Project settings:
 - resourceGroupName: swa-issue-615-rg
 - staticSiteName: swa-issue-615
 - subscriptionId: xyz
✔ Successfully setup project!
Saving project settings to swa-cli.config.json...
Updating configuration file at /tmp/swa-issue-615/swa-cli.config.json
Loading existing swa-cli.config.json file at /tmp/swa-issue-615/swa-cli.config.json

Deployment token provided via remote configuration
 - deploymentToken: <hidden>

Deploying to environment: preview

Trying to read workflow config with values:
 - appLocation: /tmp/swa-issue-615/public
 - outputLocation: /tmp/swa-issue-615/public
 - apiLocation: <undefined>
No workflow config folder found at /tmp/swa-issue-615/public/.github/workflows
Validating user workflow config (BEFORE):
 - appLocation: /tmp/swa-issue-615/public
 - outputLocation: /tmp/swa-issue-615/public
 - apiLocation: <undefined>
Validating user workflow config (AFTER):
 - appLocation: /tmp/swa-issue-615/public
 - apiLocation: <undefined>
 - outputLocation: /tmp/swa-issue-615/public
No staticwebapp.config.json found in current project
Deploying project to Azure Static Web Apps...
Fetching release metadata for version: stable. Please wait...
Writing configuration "swa-issue-615" to swa-cli.config.json
 - appLocation: public
 - outputLocation: .
 - appName: swa-issue-615
 - resourceGroupName: swa-issue-615-rg
 - version: stable
 - buildId: 1.0.020981
 - publishDate: 2022-09-29T17:37:34.4094014Z
- files:
 - linux-x64:
   - url: https://swalocaldeploy.azureedge.net/downloads/1.0.020981/linux/StaticSitesClient
   - sha: e55db21d0720a12098804559152303e66846bdd94c13a30b30be29a0fc9ae366
 - win-x64:
   - url: https://swalocaldeploy.azureedge.net/downloads/1.0.020981/windows/StaticSitesClient.exe
   - sha: 4e4eb72aef26641e236c24929c822500e956bda099ca78054112cadf20261107
 - osx-x64:
   - url: https://swalocaldeploy.azureedge.net/downloads/1.0.020981/macOS/StaticSitesClient
   - sha: e0f2ae7ec297510a1b3b9332c0dc0dd962a51adb8ea13cd4f3746d79fc24a7e9
StaticSitesClient is outdated! Expected 1.0.020981, got 1.0.020761
[swa] ✔ Downloading https://swalocaldeploy.azureedge.net/downloads/1.0.020981/linux/StaticSitesClient@1.0.020981
Checksum match: e55db21d0720a12098804559152303e66846bdd94c13a30b30be29a0fc9ae366
Saved binary to /home/wassimchegham/.swa/deploy/1.0.020981/StaticSitesClient
Saved metadata to /home/wassimchegham/.swa/deploy/StaticSitesClient.json
Deploying using /home/wassimchegham/.swa/deploy/1.0.020981/StaticSitesClient@1.0.020981
Deploying using the following options:
- env:
  - SWA_CLI_DEBUG: silly
  - SWA_RUNTIME_WORKFLOW_LOCATION: <undefined>
  - SWA_RUNTIME_CONFIG_LOCATION: <undefined>
  - SWA_RUNTIME_CONFIG: <undefined>
  - SWA_CLI_VERSION: 1.0.3-alpha
  - SWA_CLI_DEPLOY_DRY_RUN: false
  - SWA_CLI_DEPLOY_BINARY: /home/wassimchegham/.swa/deploy/1.0.020981/StaticSitesClient@1.0.020981
  - DEPLOYMENT_ACTION: upload
  - DEPLOYMENT_PROVIDER: swa-cli-1.0.3-alpha
  - REPOSITORY_BASE: /tmp/swa-issue-615/public
  - SKIP_APP_BUILD: true
  - SKIP_API_BUILD: true
  - DEPLOYMENT_TOKEN: <hidden>
  - APP_LOCATION: /tmp/swa-issue-615/public
  - API_LOCATION: <undefined>
  - CONFIG_FILE_LOCATION: <undefined>
  - VERBOSE: true
  - DEPLOYMENT_ENVIRONMENT: preview
ℹ DeploymentId: 0158ca5a-f089-4322-934f-27953cfc2e2c
ℹ
ℹ Verbose logging enabled
ℹ Build timeout not specified, defaulting to 15 minutes
ℹ App Directory Location: '/tmp/swa-issue-615/public' was found.
ℹ Looking for event info
ℹ Event info parsed from action options.
ℹ Could not get repository branch. Proceeding
ℹ Could not get repository url. Proceeding
ℹ Skipping step to build /tmp/swa-issue-615/public with Oryx
ℹ No Api directory specified. Azure Functions will not be created.
ℹ Could not find staticwebapp.config.json file.
ℹ Didn't find Oryx manifest file under location: /tmp/swa-issue-615/ss-oryx/app-manifest/oryx-manifest.toml
ℹ Determined default file to be: index.html
ℹ Either no Api directory was specified, or the specified directory was not found. Azure Functions will not be created.
ℹ Zipping App Artifacts
ℹ App Zip will be created from directory: /tmp/swa-issue-615/public
ℹ Done Zipping App Artifacts
ℹ Uploading build artifacts.
ℹ Skipping function upload as functions are identical to last successful deployment.
ℹ Finished Upload. Polling on deployment.
ℹ Status: InProgress. Time: 0.3321889(s)
ℹ Status: Succeeded. Time: 15.635655(s)
ℹ Deployment Complete :)
ℹ Thanks for using Azure Static Web Apps!
✔ Project deployed to https://kind-river-0644df51e-preview.westus2.2.azurestaticapps.net 🚀
```

</details>

**Comment by derkoe** [comment]
Just debuggend this a little more and it seems that the `swa` CLI fails because it is calling a (quite old) .NET binary `StaticSitesClient` which cannot be run on any current Linux distro (like Ubuntu 22.10).

First it fails with this error:

```
❯ /home/user/.swa/deploy/1.0.020981/StaticSitesClient
Process terminated. Couldn't find a valid ICU package installed on the system. Set the configuration flag System.Globalization.Invariant to true if you want to run with no globalization support.
   at System.Environment.FailFast(System.String)
   at System.Globalization.GlobalizationMode.GetGlobalizationInvariantMode()
   at System.Globalization.GlobalizationMode..cctor()
   at System.Globalization.CultureData.CreateCultureWithInvariantData()
   at System.Globalization.CultureData.get_Invariant()
   at System.Globalization.CultureInfo..cctor()
   at System.String.ToLowerInvariant()
   at System.Text.EncodingHelper.GetCharset()
   at System.Text.EncodingHelper.GetEncodingFromCharset()
   at System.ConsolePal.GetConsoleEncoding()
   at System.Console+<>c.<get_OutputEncoding>b__19_0()
   at System.Threading.LazyInitializer.EnsureInitializedCore[[System.__Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.__Canon ByRef, System.Object ByRef, System.Func`1<System.__Canon>)
   at System.Threading.LazyInitializer.EnsureInitialized[[System.__Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.__Canon ByRef, System.Object ByRef, System.Func`1<System.__Canon>)
   at System.Console.get_OutputEncoding()
   at System.Console.CreateOutputWriter(System.IO.Stream)
   at System.Console+<>c.<get_Out>b__26_0()
   at System.Threading.LazyInitializer.EnsureInitializedCore[[System.__Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.__Canon ByRef, System.Object ByRef, System.Func`1<System.__Canon>)
   at System.Threading.LazyInitializer.EnsureInitialized[[System.__Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.__Canon ByRef, System.Object ByRef, System.Func`1<System.__Canon>)
   at System.Console.get_Out()
   at System.ConsolePal.RefreshColors(System.ConsoleColor ByRef, System.ConsoleColor)
   at StaticSitesClient.Helpers.ConsoleWriterHelper.WriteLine(System.String, System.ConsoleColor, Boolean)
   at StaticSitesClient.Program.Main(System.String[])
zsh: IOT instruction  /home/user/.swa/deploy/1.0.020981
```

After some digging, I found setting `DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1` will fix this.

But then it will fail with "No usable version of libssl was found":

```
/home/user/.swa/deploy/1.0.020981/StaticSitesClient upload --app public --api dist --apiToken $TOKEN
DeploymentId: bd09c404-970e-4931-a93d-f9ee3543c131

App Directory Location: 'public' was found.
Looking for event info
GitHub Event Json () does not exist. Proceeding
Could not get event info. Proceeding
No usable version of libssl was found
zsh: IOT instruction  /home/user/.swa/deploy/1.0.020981/StaticSitesClient upload --app public --api 
```

**Comment by manekinekko** [comment]
cc @sulabh-msft

**Comment by derkoe** [comment]
#536 and #557 are related and also caused by a hanging or silently failing `StaticSitesClient`.

**Comment by sgollapudi77** [comment]
@derkoe  We did a new StaticSiteClient release recently, can you please check once and get back to us if you find any issue. Thanks.
We're tracking this issue at #557

**Comment by derkoe** [comment]
Thanks! The `swa deploy` works now event without setting `DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1` and passing `--no-use-keychain` and it does not hang. So, this should be fixed. 

However my app (https://github.com/derkoe/qwik-swa-demo) cannot be deployed anymore - this is the error:
```
✖ Current directory cannot be identical to or contained within artifact folders.
```
(guess I have to create another issue for that).

---

I still think that the practice of downloading the binary on deploy and stating it is not a very good practice:
1. This makes builds not reproducible - one time it fails, then it works, then it fails again. All with the same version of `@azure/static-web-apps-cli`
2. From a security standpoint this is not a good idea

I guess it would be best to either implement the API calls directly in `@azure/static-web-apps-cli` or at least bundle the binary with the npm package.

**Comment by RossMurr4y** [comment]
> I still think that downloading the binary on deploy and then starting it is not a very good practice

I have to agree with this - it not only impacts builds but also releases. They cannot be definitively reproduced down the line for disaster-recovery/rollback purposes which is particularly problematic.

**Comment by sgollapudi77** [comment]
> I guess it would be best to either implement the API calls directly in `@azure/static-web-apps-cli` or at least bundle the binary with the npm package.

@derkoe , SWA_CLI is started as local development tool, and we don't want to bundle this only for `swa deploy` purpose. 

 
> I have to agree with this - it not only impacts builds but also releases. They cannot be definitively reproduced down the line for disaster-recovery/rollback purposes which is particularly problematic.

@RossMurr4y we agree that this is problematic now, but in general StaticSiteClient releases won't happen this frequently so you won't have to download the binary again and again.

**Comment by RossMurr4y** [comment]
@sgollapudi77 its not about downloading a binary multiple times, its about keeping releases consistent. If i deploy a build artefact now, I need to know that if i have to roll back to it in 6months time, I can reliably repeat the exact same process without changed dependencies. 

If I pull down a pinned version of the swa cli that matches the original release, that meets my criteria. But it does not if that old version then goes and retrieves the latest StaticSitesClient under the hood. Though there are environment variables that allow you to define the path to the StaticSitesClient binary, it does not look like the old binaries are kept for download. So this will always be a problem until they are packaged together and reflect a fixed point in time.

**Comment by orkisz** [comment]
> 
> After some digging, I found setting `DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1` will fix this.
> 

I had the same issue. IDK if it should be mentioned in the docs to set this flag, but for sure silent error should not happen.

I saw the source code and I don't see piping strerr nor handling this stream when invoking StaticSitesClient executable. It would be nice to expose it (at least in debug mode).

**Comment by RossMurr4y** [comment]
> DK if it should be mentioned in the docs to set this flag,

So I take it this env var resolved the issue for you? Did you notice any different output at all when you applied it? 

I've set it everywhere I can think to in my deployment pipelines and am not seeing any differences. Would be good to know what to look out for in the debug logs to verify that its making an impact. I can write out the value at runtime but that doesn't tell me that the apps have picked it up and are factoring it in.

Currently have a support ticket to get the deployments going again. Because every method to deploy an app into SWA relies on StaticSitesClient, it ifs not behaving as expected theres very little else you can do but raise a ticket.

**Comment by derkoe** [comment]
I'm gonna close this because it is solved. For the other issue with the changing StaticSitesClient I've created #631

**Comment by TheRealWaldo** [comment]
This same problem happens when running swa in a dev container on an M1 Mac.  It is incorrectly downloading an x86-64 binary.

It also may not be properly accounting for exit code 255.

```
❯ ~/.swa/deploy/1.0.023121/StaticSitesClient
qemu-x86_64: Could not open '/lib64/ld-linux-x86-64.so.2': No such file or directory
```
