### ISSUE TITLE
Attempting to close CLI server does not stop all running services [Windows]

### ISSUE THREAD

**Issue by craigshoemaker** [Azure/static-web-apps-cli#96]
On **Windows**, attempting to close the CLI server using `ctrl-c` does not stop all running services. Additionally, sometimes a response is _very delayed_ after pressing `ctrl-c`, and at times there is no response at all.

## Steps to reproduce
1. Start a SWA site with the `swa start <APP_LOCATION>`
2. Type `ctrl-c` to stop the CLI server
3. Try to start the site again with `swa start <APP_LOCATION>`
4. See error 👇

## Expected behavior
When you close the CLI server using `ctrl-c`, all services are stopped so you can start it again successfully.

## Desktop
 - **OS**: Windows
 - **Browser:** n/a
 - **Version**: n/a

## Error
```
$ swa start ./__sapper__/export

INFO: Found SWA configuration file: C:\Users\cshoe\Documents\data\code\projects\website\.github\workflows\azure-static-web-apps-red-bay-09fca812.yml
>> detected runtime: node.js
[ swa] SWA listening on http://0.0.0.0:4280
[auth] events.js:288
[auth]       throw er; // Unhandled 'error' event
[auth]       ^
[auth]
[auth] Error: listen EADDRINUSE: address already in use 0.0.0.0:4242
[auth]     at Server.setupListenHandle [as _listen2] (net.js:1309:16)
[auth]     at listenInCluster (net.js:1357:12)
[auth]     at doListen (net.js:1496:7)
    at processTicksAndRejections (internal/process/task_queues.js:85:21)
[auth] Emitted 'error' event on Server instance at:
[auth]     at emitErrorNT (net.js:1336:8)
[auth]     at processTicksAndRejections (internal/process/task_queues.js:84:21) {
[auth]   code: 'EADDRINUSE',
[auth]   errno: 'EADDRINUSE',
[auth]   syscall: 'listen',
  address: '0.0.0.0',
  port: 4242
[auth] }
[ swa] events.js:288
      throw er; // Unhandled 'error' event
[ swa]       ^
[ swa]
[ swa] Error: listen EADDRINUSE: address already in use 0.0.0.0:4280
[ swa]     at Server.setupListenHandle [as _listen2] (net.js:1309:16)
    at listenInCluster (net.js:1357:12)
[ swa]     at doListen (net.js:1496:7)
[ swa]     at processTicksAndRejections (internal/process/task_queues.js:85:21)
Emitted 'error' event on Server instance at:
[ swa]     at emitErrorNT (net.js:1336:8)
[ swa]     at processTicksAndRejections (internal/process/task_queues.js:84:21) {
[ swa]   code: 'EADDRINUSE',
  errno: 'EADDRINUSE',
  syscall: 'listen',
[ swa]   address: '0.0.0.0',
[ swa]   port: 4280
[ swa] }
[ swa] node ../proxy/server.js exited with code 1
[ swa] node ../proxy/server.js restarted
[auth] node ../auth/server.js --host=0.0.0.0 --port=4242 exited with code 1
[auth] node ../auth/server.js --host=0.0.0.0 --port=4242 restarted
[ app] Starting up http-server, serving C:\Users\cshoe\Documents\data\code\projects\website\__sapper__\export
[ app] Available on:
[ app]   http://192.168.1.2:4200
[ app]   http://100.64.76.144:4200
[ app]   http://127.0.0.1:4200
[ app]   http://172.22.16.1:4200
[ app] Unhandled requests will be served from: http://0.0.0.0:4280/?
[ app] Hit CTRL-C to stop the server
[auth] events.js:288
      throw er; // Unhandled 'error' event
[auth]       ^
[auth]
[auth] Error: listen EADDRINUSE: address already in use 0.0.0.0:4242
[auth]     at Server.setupListenHandle [as _listen2] (net.js:1309:16)
    at listenInCluster (net.js:1357:12)
    at doListen (net.js:1496:7)
    at processTicksAndRejections (internal/process/task_queues.js:85:21)
[auth] Emitted 'error' event on Server instance at:
    at emitErrorNT (net.js:1336:8)
[auth]     at processTicksAndRejections (internal/process/task_queues.js:84:21) {
[auth]   code: 'EADDRINUSE',
[auth]   errno: 'EADDRINUSE',
  syscall: 'listen',
  address: '0.0.0.0',
[auth]   port: 4242
[auth] }
[ swa] SWA listening on http://0.0.0.0:4280
[ swa] events.js:288
      throw er; // Unhandled 'error' event
[ swa]       ^
[ swa]
[ swa] Error: listen EADDRINUSE: address already in use 0.0.0.0:4280
[ swa]     at Server.setupListenHandle [as _listen2] (net.js:1309:16)
    at listenInCluster (net.js:1357:12)
[ swa]     at doListen (net.js:1496:7)
    at processTicksAndRejections (internal/process/task_queues.js:85:21)
[ swa] Emitted 'error' event on Server instance at:
[ swa]     at emitErrorNT (net.js:1336:8)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
[ swa]   code: 'EADDRINUSE',
[ swa]   errno: 'EADDRINUSE',
[ swa]   syscall: 'listen',
[ swa]   address: '0.0.0.0',
  port: 4280
[ swa] }
[auth] node ../auth/server.js --host=0.0.0.0 --port=4242 exited with code 1
[ swa] node ../proxy/server.js exited with code 1
```

**Comment by manekinekko** [comment]
Does it happen all the time? Or is it random?

**Comment by craigshoemaker** [comment]
Sadly, it seem to happen intermittently.

**Comment by manekinekko** [comment]
@craigshoemaker would you mind giving this another try (`main` branch) and let me know if you are still having this issue?

**Comment by manekinekko** [comment]
@craigshoemaker  would you mind giving this another try (main branch) and let me know if you are still having this issue?

**Comment by Reshmi-Sriram** [comment]
This issue should be resolved. @craigshoemaker - please do reopen if you still face any issues.
